---
# tasks file for redmine_cas

- name: Fetch from git
  git:
    accept_hostkey: yes
    ssh_opts: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    repo: "{{ plugin_repo }}"
    dest: "{{ redmine_dir }}/plugins/{{ plugin_name }}"
  notify: restart redmine

- name: Ensure directory permissions
  file:
    path: "{{ redmine_dir }}/plugins/{{ plugin_name }}"
    owner: "{{ sudo_user }}"
    group: "{{ sudo_user }}"
    recurse: yes
    state: directory
  notify: restart redmine

- name: Install plugin gems
  command: bundle install --without development test
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    RAILS_ENV: production
  # sudo_user: "{{ sudo_user }}"
  notify: restart redmine

- name: Migrate plugins
  command: bundle exec rake redmine:plugins:migrate
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    RAILS_ENV: production
  sudo_user: "{{ sudo_user }}"
  notify: restart redmine
